source ENV['GEM_SOURCE'] || "https://rubygems.org"

gem 'rspec'
gem 'rspec_junit_formatter'
gem 'pupperware',
  :git => 'https://github.com/puppetlabs/pupperware.git',
  :ref => 'main',
  :glob => 'gem/*.gemspec'
